### ISSUE TITLE
saved models are not displayed well.

### ISSUE THREAD

**Issue by kaaiian** [anthony-wang/CrabNet#1]
use_crabnet.py has a function "list_saved_models". 

This function lists models, but they aren't usable when you copy them. We should clean this up so you can double click on a model and copy it directly into the predict_crabnet() function.

**Comment by anthony-wang** [comment]
Fixed with https://github.com/anthony-wang/CrabNet/commit/c44b48d711e894b451eba088013c818aafdacd82
