### ISSUE TITLE
Is Python 3.8+ a known requirement, or are earlier versions just untested?

### ISSUE THREAD

**Issue by sgbaird** [anthony-wang/CrabNet#12]
There's another repository I'm trying to link up that specified Python 3.7 as a dependency.

**Comment by anthony-wang** [comment]
Hey, please see my comment here: https://github.com/anthony-wang/CrabNet/issues/11#issuecomment-918394528

TL;DR: I _think_ CrabNet will run with slightly newer/older versions of PyTorch/CUDA toolkit/Python, but these rely on the individual packages' compatibility with different regions and I have not tested these combinations.
