### ISSUE TITLE
What is KingCrab?

### ISSUE THREAD

**Issue by sgbaird** [anthony-wang/CrabNet#3]

**Comment by anthony-wang** [comment]
https://github.com/anthony-wang/CrabNet/blob/master/crabnet/kingcrab.py
🙂

**Comment by sgbaird** [comment]
Right, I guess I mean what's different about it compared to what was used in the ArXiv paper? Thanks Anthony!

**Comment by anthony-wang** [comment]
The updated preprint is [up on ChemRxiv](https://doi.org/10.26434/chemrxiv.11869026) if you want all the details of the new CrabNet (/ KingCrab), but in summary we greatly improved the model performance, expanded the benchmark datasets and included Roost / ElemNet / Automatminer benchmarks, and also offered a first look at attention-based visualizations of materials chemistries.

All the changes can be seen here in the Github repo and also you can refer to the different versions of the preprint on ChemRxiv:
- v1 (old): https://chemrxiv.org/articles/preprint/Compositionally-Restricted_Attention-Based_Network_for_Materials_Property_Prediction/11869026/1
- v2 (current): https://chemrxiv.org/articles/preprint/Compositionally-Restricted_Attention-Based_Network_for_Materials_Property_Prediction/11869026/2
