### ISSUE TITLE
Do any of the CSV files in data/element_properties/ need citations? (e.g. in a README in the element_properties folder)

### ISSUE THREAD

**Issue by sgbaird** [anthony-wang/CrabNet#9]
Trying to track down the source of oliynyk.csv

**Comment by sgbaird** [comment]
For Oliynyk, this one perhaps?
(1) Oliynyk, A. O.; Antono, E.; Sparks, T. D.; Ghadbeigi, L.; Gaultois, M. W.; Meredig, B.; Mar, A. High-Throughput Machine-Learning-Driven Synthesis of Full-Heusler Compounds. Chemistry of Materials 2016, 28 (20). https://doi.org/10.1021/acs.chemmater.6b02724.

**Comment by anthony-wang** [comment]
@sgbaird yes that should be the one, but I currently cannot find the actual CSV for download somewhere. I think it may be best to ask Ka'ai since he was the one who originally gathered that data.
